### ISSUE TITLE
Error when installing databricks-dbapi on Azure Databricks

### ISSUE THREAD

**Issue by maxritter** [crflynn/databricks-dbapi#14]
Hi there,

I am getting the following error when trying to install databricks-dbapi on my Databricks Cluster on Azure:

```
List(/databricks/python/bin/pip, install, databricks-dbapi[sqlalchemy]==0.5.0, --disable-pip-version-check) exited with code 1.   ERROR: Command errored out with exit status 1:
  In file included from sasl/saslwrapper.cpp:254:0:
  sasl/saslwrapper.h:22:10: fatal error: sasl/sasl.h: No such file or directory
   #include <sasl/sasl.h>
            ^~~~~~~~~~~~~
  compilation terminated.
```

Seems like sasl lib is missing, any idea how it can be solved? I tried Databricks version 7.5 and 8.0 Beta, problem is the same for both

**Comment by climeworks-db** [comment]
Fixed it by running:
`%sh apt-get update && apt-get install libsasl2-dev -y && pip install databricks-dbapi[sqlalchemy] && exit `

**Comment by crflynn** [comment]
libsasl2 is a requirement for pyhive.

linux: apt-get update && apt-get install libsasl2-dev -y 
mac: brew install libsasl2

These should enable the installation.
