### ISSUE TITLE
Support Databricks SQL endpoints using pyhive

### ISSUE THREAD

**Issue by Tom-Newton** [crflynn/databricks-dbapi#24]
Hello! Thanks for making this it has been very helpful and I have a suggestion for an improvement. 

We have found the `pyodbc` SQL Alchemy dialect quite problematic. e.g. case statements on boolean columns add inserts don't seem to work. 
```
query = session.query(case([(Model.some_boolean_column, 1)],else_=0) ) 
```
```
session.add(Model(column="value"))
session.commit()
```
I believe this is because most of the `pyodbc` dialect is just inheriting the [`pyhive` library](https://github.com/dropbox/PyHive/blob/master/pyhive/sqlalchemy_hive.py). We want to use Databricks SQL endpoints so I found a workaround adding support for SQL endpoints with the pyhive mode. https://github.com/Tom-Newton/databricks-dbapi?organization=Tom-Newton&organization=Tom-Newton . It was quite simple to do really and I thought you might want to make a similar change to this primary repo so others can benefit. I just used the [Databricks SQL Connector for Python](https://docs.microsoft.com/en-gb/azure/databricks/dev-tools/python-sql-connector) for making pyhive connections. This supports general purpose compute clusters and SQL endpoints.

**Comment by crflynn** [comment]
That looks relatively new, and since it looks to be built specifically for databricks it might supercede the pyhive/odbc implementation here.

Were all of the functionality issues solved by using `databricks-sql-connector` and the pyhive dialect from `databricks-dbapi`? Does it work for both types of clusters?

**Comment by Tom-Newton** [comment]
Using pyhive solved all our functionality issues. I have explicitly tested General purpose clusters only a SQL endpoint but the docs about `databricks-sql-connector` say it supports both.

**Comment by sahilprasad** [comment]
Can confirm that it's working for both.

@Tom-Newton @crflynn thoughts on upstreaming these changes?

**Comment by Tom-Newton** [comment]
Personally I'm keen to upstream the changes.

**Comment by sahilprasad** [comment]
@Tom-Newton can you make a PR when you have the chance? or is there anything else you'd like to add to the fork beforehand?

**Comment by crflynn** [comment]
I was planning on just deprecating this lib in favor of a new one with just the dialect that uses the connector as a driver. I'm actually working on it right now.

**Comment by crflynn** [comment]
Here it is: https://github.com/crflynn/sqlalchemy-databricks

**Comment by sahilprasad** [comment]
@crflynn looks great! will give this a try tonight, thanks for the amazingly quick turnaround!

**Comment by crflynn** [comment]
Please feel free to PR any changes I might have missed

**Comment by crflynn** [comment]
For anyone who comes across this issue, please refer to 
* https://docs.databricks.com/dev-tools/python-sql-connector.html
* https://pypi.org/project/databricks-sql-connector/
* https://github.com/crflynn/sqlalchemy-databricks
* https://pypi.org/project/sqlalchemy-databricks/

**Comment by crflynn** [comment]
Also, thanks @Tom-Newton for figuring this out. Much easier now that databricks supports their own dbapi
